apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - cloudnative-pg
  # - postgres
  - discovery/consul
  - databases/postgres

#  - kafka
#  - keycloak
#  - milvus
#  - minio
#  - dragonflydb