apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic

metadata:
  name: users-events
  namespace: mrun-messaging

  labels:
    strimzi.io/cluster: mrun-kafka

spec:
  topicName: users.events

  partitions: 6

  replicas: 3


---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic

metadata:
  name: cards-events
  namespace: mrun-messaging

  labels:
    strimzi.io/cluster: mrun-kafka

spec:
  topicName: cards.events

  partitions: 6

  replicas: 3


---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic

metadata:
  name: camera-events
  namespace: mrun-messaging

  labels:
    strimzi.io/cluster: mrun-kafka

spec:
  topicName: camera.events

  partitions: 6

  replicas: 3


---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic

metadata:
  name: similarity-jobs
  namespace: mrun-messaging

  labels:
    strimzi.io/cluster: mrun-kafka

spec:
  topicName: similarity.jobs

  partitions: 6

  replicas: 3