apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: mrun-messaging
  labels:
    strimzi.io/cluster: mrun-face-platform
spec:
  replicas: 3
  roles:
    - controller
    - broker
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  storage:
    type: persistent-claim
    size: 50Gi
    deleteClaim: false