apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: users-service
spec:

  selector:

    matchLabels:
      app: users-service

  endpoints:

    - port: http

      path: /metrics

      interval: 30s