apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics-monitor
  namespace: mrun-messaging
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: main-cluster
      strimzi.io/kind: Kafka
  namespaceSelector:
    matchNames:
      - messaging
  endpoints:
    - port: tcp-prometheus
      interval: 30s
      path: /metrics