apiVersion: v1
kind: Endpoints
metadata:
  name: postgresql
  namespace: mrun-database
subsets:
  - addresses:
      - ip: 10.239.14.112
    ports:
      - name: postgres
        port: 5432
        protocol: TCP