apiVersion: v1
kind: ConfigMap

metadata:
  name: api-gateway-config
  namespace: mrun-apps

data:
  APP_NAME: api-gateway

  APP_ENV: development

  APP_VERSION: "0.1.0"

  LOG_LEVEL: debug

  CONSUL_HOST: consul.mrun-system.svc.cluster.local

  CONSUL_PORT: "8500"