apiVersion: v1
kind: ConfigMap

metadata:
  name: api-gateway-config
  namespace: mrun-apps

data:
  NODE_ENV: "production"
  SERVICE_NAME: "api-gateway"
  PORT: "80"

  LOG_LEVEL: "info"

  CONSUL_HOST: "consul.mrun-system.svc.cluster.local"
  CONSUL_PORT: "8500"

  KAFKA_BROKERS: "kafka.mrun-system.svc.cluster.local:9092"

  KEYCLOAK_URL: "http://keycloak.mrun-security.svc.cluster.local:8080"

  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.mrun-monitoring.svc.cluster.local:4318"