apiVersion: v1
kind: ConfigMap

metadata:
  name: analytics-service-config
  namespace: mrun-apps

data:
  ENVIRONMENT: "production"
  PORT: "3005"
  LOG_LEVEL: "INFO"

  CONSUL_HOST: "consul.mrun-system.svc.cluster.local"
  CONSUL_PORT: "8500"

  #######################  START CLICKHOUSE ##########################
  CLICKHOUSE_HOST: "clickhouse.mrun-system.svc.cluster.local"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_DATABASE: "mrun"
  CLICKHOUSE_ENABLED: "true"
  #######################  END CLICKHOUSE ##########################
