apiVersion: apps/v1
kind: Deployment

metadata:
  name: cards-service

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: cards-service

          imagePullPolicy: Never

          env:
            - name: APP_ENV
              value: development