apiVersion: v1
kind: Endpoints
metadata:
  name: kafka
  namespace: mrun-messaging
subsets:
  - addresses:
      - ip: 10.239.14.112
    ports:
      - name: kafka
        port: 9092
        protocol: TCP