apiVersion: v1
kind: ConfigMap

metadata:
  name: notification-service-config
  namespace: mrun-apps

data:
  ENVIRONMENT: "production"
  PORT: "3004"
  LOG_LEVEL: "INFO"

  CONSUL_HOST: "consul.mrun-system.svc.cluster.local"
  CONSUL_PORT: "8500"

  KAFKA_BROKERS: "kafka.mrun-messaging.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "notification-service"
  KAFKA_GROUP_ID: "notification-workers"
  KAFKA_ENABLED: "true"

  #######################  START DRAGONFLY ##########################
  DRAGONFLY_HOST: "dragonfly.mrun-system.svc.cluster.local"
  DRAGONFLY_PORT: "6379"
  DRAGONFLY_ENABLED: "true"
  #######################  END DRAGONFLY ##########################

  NOTIFY_RATE_LIMIT_PER_MINUTE: "30"
  NOTIFY_DEDUPE_TTL_SECONDS: "300"
