apiVersion: v1
kind: ConfigMap

metadata:
  name: users-service-config
  namespace: mrun-apps

data:
  NODE_ENV: production

  PORT: "3000"

  LOG_LEVEL: info

  CONSUL_HOST: consul.mrun-system.svc.cluster.local

  CONSUL_PORT: "8500"

  KAFKA_BROKERS: kafka.mrun-system.svc.cluster.local:9092

  KEYCLOAK_URL: http://keycloak.mrun-security.svc.cluster.local:8080

  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.mrun-monitoring.svc.cluster.local:4318

  #######################  START POSTGRES ##########################
  DB_HOST: users-db-rw.mrun-database.svc.cluster.local
  DB_PORT: "5432"
  DB_USERNAME: "users_db"
  DB_NAME: "users"
  #######################  END POSTGRES ##########################
