apiVersion: v1
kind: Endpoints
metadata:
  name: kafka
  namespace: mrun-messaging
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: external-service
subsets:
  - addresses:
      - ip: 172.19.0.10
    ports:
      - name: kafka
        port: 9092
        protocol: TCP