apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mrun-apps

resources:
  - ../../../platform/external-services

patches:
  - path: patches/api-gateway.yaml
  - path: patches/users-service.yaml
  - path: patches/cards-service.yaml
  - path: patches/kafka-endpoints.yaml
  - path: patches/postgresql-endpoints.yaml