apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mrun-apps

resources:
  - ../../base

patches:
  - path: patches/api-gateway.yaml
  - path: patches/users-service.yaml
  - path: patches/cards-service.yaml