apiVersion: v1
kind: ConfigMap
metadata:
  name: cards-service-config

data:
  NODE_ENV: production

  PORT: "3000"

  DATABASE_HOST: postgres

  DATABASE_PORT: "5432"

  DATABASE_NAME: cards_db

  DATABASE_USER: postgres

  KAFKA_BROKERS: kafka:9092

  CONSUL_HOST: consul

  CONSUL_PORT: "8500"

  KEYCLOAK_URL: http://keycloak:8080

  LOG_LEVEL: info