apiVersion: v1
kind: ConfigMap

metadata:
  name: cards-service-config
  namespace: mrun-apps

data:

  APP_NAME: cards-service
  APP_ENV: production
  LOG_LEVEL: info

  HOST: "0.0.0.0"
  PORT: "8000"

  ####################################
  # PostgreSQL
  ####################################

  POSTGRES_HOST: cards-db-rw.mrun-database.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "cards_db"
  DB_NAME: "cards"

  ####################################
  # DragonFlyDB
  ####################################

  CACHE_HOST: dragonfly.mrun-system.svc.cluster.local
  CACHE_PORT: "6379"

  ####################################
  # MinIO
  ####################################

  MINIO_ENDPOINT: minio.mrun-system.svc.cluster.local:9000
  MINIO_BUCKET: cards-images
  MINIO_SECURE: "false"

  ####################################
  # Kafka
  ####################################

  KAFKA_BROKERS: kafka.mrun-system.svc.cluster.local:9092

  CARD_EVENTS_TOPIC: card.events

  ####################################
  # Consul
  ####################################

  CONSUL_HOST: consul.mrun-system.svc.cluster.local
  CONSUL_PORT: "8500"

  ####################################
  # Internal Services
  ####################################

  CAMERA_SERVICE_URL: http://camera-service.mrun-apps.svc.cluster.local:8000

  SIMILARITY_SERVICE_URL: http://similarity-service.mrun-apps.svc.cluster.local:8000