apiVersion: apps/v1
kind: Deployment

metadata:
  name: cards-service
  namespace: mrun-apps

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: cards-service

  template:

    metadata:
      labels:
        app: cards-service

    spec:

      serviceAccountName: cards-service

      securityContext:
        fsGroup: 1000

      containers:

        - name: cards-service

          image: mrun/cards-service:latest

          imagePullPolicy: IfNotPresent

          ports:

            - containerPort: 3000

          envFrom:

            - configMapRef:
                name: cards-service-config

            - secretRef:
                name: cards-service-secret

          resources:

            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:

            httpGet:
              path: /health
              port: 3000

            periodSeconds: 5
            failureThreshold: 30

          readinessProbe:

            httpGet:
              path: /health
              port: 3000

            periodSeconds: 5

          livenessProbe:

            httpGet:
              path: /health
              port: 3000

            periodSeconds: 10