apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - podmonitor.yaml
#  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: users-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: mrun-platform