apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: cards-service

spec:
  selector:
    matchLabels:
      app: cards-service

  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s