apiVersion: v1
kind: Secret

metadata:
  name: cards-service-secret
  namespace: mrun-apps

type: Opaque

stringData:

  POSTGRES_USER: cards_user
  POSTGRES_PASSWORD: 123456

  MINIO_ACCESS_KEY: minio
  MINIO_SECRET_KEY: 123456