apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: cards-service

spec:
  selector:
    matchLabels:
      app: cards-service

  endpoints:
    - port: http
      path: /metrics
      interval: 15s