apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-all-internal
  namespace: mrun-security

spec:
  podSelector: {}

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - {}

  egress:
    - {}