apiVersion: v1
kind: ResourceQuota

metadata:
  name: security-resource-quota
  namespace: mrun-security

spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi

    limits.cpu: "2"
    limits.memory: 4Gi

    pods: "10"

    services: "20"

    persistentvolumeclaims: "20"

    configmaps: "50"

    secrets: "50"