apiVersion: v1
kind: Service

metadata:
  name: consul

spec:
  clusterIP: None

  selector:
    app: consul

  ports:
    - name: http
      port: 8500
      targetPort: 8500

    - name: rpc
      port: 8300
      targetPort: 8300

    - name: serf-lan
      port: 8301
      targetPort: 8301

    - name: serf-wan
      port: 8302
      targetPort: 8302

    - name: dns
      port: 8600
      protocol: UDP
      targetPort: 8600