apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser

metadata:
  name: cards-service
  namespace: mrun-messaging
  labels:
    strimzi.io/cluster: kafka

spec:
  authentication:
    type: scram-sha-512