apiVersion: v1
kind: ConfigMap

metadata:
  name: audit-service-config
  namespace: mrun-apps

data:
  ENVIRONMENT: "production"
  PORT: "3003"
  LOG_LEVEL: "INFO"

  CONSUL_HOST: "consul.mrun-system.svc.cluster.local"
  CONSUL_PORT: "8500"

  KAFKA_BROKERS: "kafka.mrun-messaging.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "audit-service"
  KAFKA_GROUP_ID: "audit-workers"
  KAFKA_ENABLED: "true"

  #######################  START CLICKHOUSE ##########################
  CLICKHOUSE_HOST: "clickhouse.mrun-system.svc.cluster.local"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_DATABASE: "mrun"
  CLICKHOUSE_ENABLED: "true"
  #######################  END CLICKHOUSE ##########################
