apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: users-service

spec:
  selector:
    matchLabels:
      app: users-service

  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s