apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: similarity.events
  namespace: mrun-messaging
  labels:
    strimzi.io/cluster: main-cluster
spec:
  partitions: 6 # Higher partition count for intensive GPU/ML workload processing
  replicas: 3
  config:
    retention.ms: 259200000 # 3 Days
    segment.bytes: 1073741824