apiVersion: v1
kind: Secret

metadata : 
  name: postgres-secret
  namespace: mrun-system

type: Opaque

stringData:
  POSTGRES_DB: "mrun_face_platform"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"