apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool

metadata:
  name: kafka
  namespace: mrun-messaging
  labels:
    strimzi.io/cluster: mrun-face-platform


spec:
  replicas: 3

  roles:
    - controller
    - broker

  storage:
    type: persistent-claim
    size: 20Gi
    deleteClaim: false