apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka

metadata:
  name: mrun-face-platform
  namespace: mrun-messaging
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled

spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3

    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false

  entityOperator:
    topicOperator: {}
    userOperator: {}