apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: enrollment-service
  namespace: mrun-apps

spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: enrollment-service
