apiVersion: v1
kind: Secret

metadata:
  name: enrollment-service-secret
  namespace: mrun-apps

type: Opaque

stringData:
  DB_PASSWORD: "change-me"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
