apiVersion: v1
kind: ConfigMap

metadata:
  name: milvus-config
  namespace: mrun-system

data:
  ETCD_ENDPOINTS: "etcd.mrun-system.svc.cluster.local:2379"
  MINIO_ADDRESS: "minio.mrun-system.svc.cluster.local:9000"
  MINIO_BUCKET_NAME: "milvus"
  COMMON_STORAGETYPE: "minio"
